# Generated by Django 3.0.3 on 2020-02-15 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=550)),
                ('recrutement', models.BooleanField()),
                ('lvlMinRecrutement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=550)),
                ('recrutement', models.BooleanField()),
                ('lvlMinRecrutement', models.IntegerField()),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Alliance')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('classe', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=550)),
                ('pvpm', models.CharField(max_length=3)),
                ('dbook', models.CharField(max_length=40)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Guild')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Server')),
            ],
        ),
        migrations.AddField(
            model_name='guild',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Server'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Server'),
        ),
    ]
