# Generated by Django 3.0.3 on 2020-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DofusClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pvpm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='classe',
            new_name='DofusClasse',
        ),
        migrations.RemoveField(
            model_name='server',
            name='name',
        ),
        migrations.AddField(
            model_name='guild',
            name='pvpm',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alliance',
            name='server',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='guild',
            name='server',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='pvpm',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='server',
            field=models.CharField(max_length=30),
        ),
    ]
