# Generated by Django 3.0.3 on 2020-02-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200215_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pvpm',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
